P8105\_hw1\_qh2251
================
Paulina Han
2021/9/23

# Problem 1

``` r
set.seed(12)

df_1 = tibble(
  vec_numeric = rnorm(10),
  vec_logical = vec_numeric>0,
  vec_char = c("a", "b", "c", "d","e","f","g","h","i","j"),
  vec_factor = factor(c("blue","blue","blue","red","red","red","yellow","yellow","yellow","yellow"))
  )

mean(pull(df_1,vec_numeric))
```

    ## [1] -0.4672139

``` r
mean(pull(df_1,vec_logical))
```

    ## [1] 0.2

``` r
mean(pull(df_1,vec_char))
```

    ## Warning in mean.default(pull(df_1, vec_char)): 参数不是数值也不是逻辑值：回覆NA

    ## [1] NA

``` r
mean(pull(df_1,vec_factor))
```

    ## Warning in mean.default(pull(df_1, vec_factor)): 参数不是数值也不是逻辑值：回覆
    ## NA

    ## [1] NA

The numerical and logical vectors work,but the character and factor
vectors don’t work.

``` r
mean(as.numeric(pull(df_1,vec_logical)))
mean(as.numeric(pull(df_1,vec_char)))
mean(as.numeric(pull(df_1,vec_factor)))
```

the `mean` function works for the converted logical vector and the
converted factor vector.However the `mean` function doesn’t work for the
converted character vector.

the `as.numeric` function set TRUE to 1 and FALSE to 0 for the logical
vector.the `as.numeric` function set “blue” to 1,“red” to 2,“yellow” to
3 for the factor vector. In this way the `mean` function works. All
characters were converted to NA by `as.numeric` function so it won’t
work for the `mean` function.

So when you try to take the mean of a vector , you have to make sure it
is a numerical vector.logical vectors can be treated as numerical
vectors by default of `mean`function.

# Problem 2

``` r
library(palmerpenguins)

#load the data from the package
data("penguins", package = "palmerpenguins")

#name and important values of the data
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

``` r
Adelie = sum(pull(penguins,species) == 'Adelie')
Chinstrap = sum(pull(penguins,species) == 'Chinstrap')
Gentoo = sum(pull(penguins,species) == 'Gentoo')

skimr::skim(penguins)
```

|                                                  |          |
|:-------------------------------------------------|:---------|
| Name                                             | penguins |
| Number of rows                                   | 344      |
| Number of columns                                | 8        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |          |
| Column type frequency:                           |          |
| factor                                           | 3        |
| numeric                                          | 5        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |          |
| Group variables                                  | None     |

Data summary

**Variable type: factor**

| skim\_variable | n\_missing | complete\_rate | ordered | n\_unique | top\_counts                 |
|:---------------|-----------:|---------------:|:--------|----------:|:----------------------------|
| species        |          0 |           1.00 | FALSE   |         3 | Ade: 152, Gen: 124, Chi: 68 |
| island         |          0 |           1.00 | FALSE   |         3 | Bis: 168, Dre: 124, Tor: 52 |
| sex            |         11 |           0.97 | FALSE   |         2 | mal: 168, fem: 165          |

**Variable type: numeric**

| skim\_variable      | n\_missing | complete\_rate |    mean |     sd |     p0 |     p25 |     p50 |    p75 |   p100 | hist  |
|:--------------------|-----------:|---------------:|--------:|-------:|-------:|--------:|--------:|-------:|-------:|:------|
| bill\_length\_mm    |          2 |           0.99 |   43.92 |   5.46 |   32.1 |   39.23 |   44.45 |   48.5 |   59.6 | ▃▇▇▆▁ |
| bill\_depth\_mm     |          2 |           0.99 |   17.15 |   1.97 |   13.1 |   15.60 |   17.30 |   18.7 |   21.5 | ▅▅▇▇▂ |
| flipper\_length\_mm |          2 |           0.99 |  200.92 |  14.06 |  172.0 |  190.00 |  197.00 |  213.0 |  231.0 | ▂▇▃▅▂ |
| body\_mass\_g       |          2 |           0.99 | 4201.75 | 801.95 | 2700.0 | 3550.00 | 4050.00 | 4750.0 | 6300.0 | ▃▇▆▃▂ |
| year                |          0 |           1.00 | 2008.03 |   0.82 | 2007.0 | 2007.00 | 2008.00 | 2009.0 | 2009.0 | ▇▁▇▁▇ |

``` r
#size of the data set
row = nrow(penguins)
col = ncol(penguins)

#mean flipper length(removing all NAs)
mean=mean(pull(penguins,flipper_length_mm),na.rm = TRUE)
```

The species is a factor variable which has 152 penguins, 68 penguins and
124.

There are 344s and 8s in the data set. The mean flipper length
is200.9152047.

``` r
#drawing a  plot
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species )) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](P8105_hw1_qh2251_files/figure-gfm/unnamed-chunk-5-1.png)<!-- -->

``` r
#save the plot
ggsave("scatter_plot.pdf", height = 4, width = 6)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).
